// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyMDb.Models;

#nullable disable

namespace MyMDb.Migrations
{
    [DbContext(typeof(MyMDbContext))]
    [Migration("20220801123159_NewEntitiesAdded")]
    partial class NewEntitiesAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MyMDb.Models.Actor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BornDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CityBorn")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("CountryBorn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Actors");
                });

            modelBuilder.Entity("MyMDb.Models.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<Guid>("TVShowId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.HasIndex("TVShowId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("MyMDb.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("TVShowId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("TVShowId");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("MyMDb.Models.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<Guid?>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovieImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TVShowId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("MovieId");

                    b.HasIndex("MovieImageId")
                        .IsUnique();

                    b.HasIndex("TVShowId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("MyMDb.Models.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Budget")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("Gross")
                        .HasColumnType("int");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("MyMDb.Models.MovieActor", b =>
                {
                    b.Property<Guid>("MovieActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MovieActorId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("MoviesActors");
                });

            modelBuilder.Entity("MyMDb.Models.TVShow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Budget")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("Gross")
                        .HasColumnType("int");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("TVShows");
                });

            modelBuilder.Entity("MyMDb.Models.TVShowActor", b =>
                {
                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TVShowActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("int");

                    b.HasKey("ActorId", "TVShowActorId");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("TVShowActorId");

                    b.ToTable("TVShowActors");
                });

            modelBuilder.Entity("MyMDb.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MyMDb.Models.UserActor", b =>
                {
                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ActorUserId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("UsersActors");
                });

            modelBuilder.Entity("MyMDb.Models.UserMovie", b =>
                {
                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovieUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MovieId", "MovieUserId");

                    b.HasIndex("MovieUserId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersMovies");
                });

            modelBuilder.Entity("MyMDb.Models.UserTVShow", b =>
                {
                    b.Property<Guid>("TVShowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TVShowUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TVShowId", "TVShowUserId");

                    b.HasIndex("TVShowUserId");

                    b.ToTable("UserTVShows");
                });

            modelBuilder.Entity("MyMDb.Models.Episode", b =>
                {
                    b.HasOne("MyMDb.Models.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyMDb.Models.TVShow", "TVShow")
                        .WithMany("Episodes")
                        .HasForeignKey("TVShowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("TVShow");
                });

            modelBuilder.Entity("MyMDb.Models.Genre", b =>
                {
                    b.HasOne("MyMDb.Models.Movie", "Movie")
                        .WithMany("Genres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyMDb.Models.TVShow", null)
                        .WithMany("Genres")
                        .HasForeignKey("TVShowId");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MyMDb.Models.Image", b =>
                {
                    b.HasOne("MyMDb.Models.Actor", null)
                        .WithMany("Photos")
                        .HasForeignKey("ActorId");

                    b.HasOne("MyMDb.Models.Movie", null)
                        .WithMany("MovieImages")
                        .HasForeignKey("MovieId");

                    b.HasOne("MyMDb.Models.Movie", "Movie")
                        .WithOne("Image")
                        .HasForeignKey("MyMDb.Models.Image", "MovieImageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyMDb.Models.TVShow", null)
                        .WithMany("MovieImages")
                        .HasForeignKey("TVShowId");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MyMDb.Models.MovieActor", b =>
                {
                    b.HasOne("MyMDb.Models.Actor", "Actor")
                        .WithMany("Movies")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyMDb.Models.Movie", "Movie")
                        .WithMany("Actors")
                        .HasForeignKey("MovieActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MyMDb.Models.TVShow", b =>
                {
                    b.HasOne("MyMDb.Models.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("MyMDb.Models.TVShowActor", b =>
                {
                    b.HasOne("MyMDb.Models.Actor", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyMDb.Models.Episode", null)
                        .WithMany("Actors")
                        .HasForeignKey("EpisodeId");

                    b.HasOne("MyMDb.Models.TVShow", "TVShow")
                        .WithMany("Actors")
                        .HasForeignKey("TVShowActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("TVShow");
                });

            modelBuilder.Entity("MyMDb.Models.UserActor", b =>
                {
                    b.HasOne("MyMDb.Models.Actor", "Actor")
                        .WithMany("UsersActors")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyMDb.Models.User", "User")
                        .WithMany("UsersActors")
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyMDb.Models.UserMovie", b =>
                {
                    b.HasOne("MyMDb.Models.Movie", "Movie")
                        .WithMany("UsersMovie")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyMDb.Models.User", "User")
                        .WithMany("RatedMovies")
                        .HasForeignKey("MovieUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyMDb.Models.User", null)
                        .WithMany("WatchList")
                        .HasForeignKey("UserId");

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyMDb.Models.UserTVShow", b =>
                {
                    b.HasOne("MyMDb.Models.TVShow", "TVShow")
                        .WithMany("UsersTVShow")
                        .HasForeignKey("TVShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyMDb.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("TVShowUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TVShow");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyMDb.Models.Actor", b =>
                {
                    b.Navigation("Movies");

                    b.Navigation("Photos");

                    b.Navigation("UsersActors");
                });

            modelBuilder.Entity("MyMDb.Models.Episode", b =>
                {
                    b.Navigation("Actors");
                });

            modelBuilder.Entity("MyMDb.Models.Movie", b =>
                {
                    b.Navigation("Actors");

                    b.Navigation("Genres");

                    b.Navigation("Image")
                        .IsRequired();

                    b.Navigation("MovieImages");

                    b.Navigation("UsersMovie");
                });

            modelBuilder.Entity("MyMDb.Models.TVShow", b =>
                {
                    b.Navigation("Actors");

                    b.Navigation("Episodes");

                    b.Navigation("Genres");

                    b.Navigation("MovieImages");

                    b.Navigation("UsersTVShow");
                });

            modelBuilder.Entity("MyMDb.Models.User", b =>
                {
                    b.Navigation("RatedMovies");

                    b.Navigation("UsersActors");

                    b.Navigation("WatchList");
                });
#pragma warning restore 612, 618
        }
    }
}
